harness.sh, network/client.go, network/hub.go, network/limiter.go, network/message.go, poolclient/client.go
This fixes a couple of bugs in the rate limiting code, sets the maximum message size and applies it as the read limit. It also properly handles too many request messages to clients.
=> multi: rework request rate limiting.

dividend/payment_test.go, dividend/share.go, dividend/share_test.go
This renames the share struct's stakeholder field to account because it better describes the field.
=> the dividend: update share struct

dividend/share.go, dividend/share_test.go, go.mod, network/client.go, network/conversion_test.go, network/hub.go, poolclient/cpuminer.go
Target conversion helpers and  tests have been added as well as fixes to bugs with the pool target calculation, the active network is also incorporated. The CPU miner has also been updated to convert provided targets from work notifications and use that instead of the header bits.
=> multi: add target conversion tests.

dividend/payment.go, dividend/payment_test.go, dividend/share_test.go, network/acceptedwork.go
This adds a cursor iteration/deletion test and updates call sites accordingly. Test assertions for PPSEligibleShares have also been simplified.
=> multi: add cursor iteration/deletion test.

dividend/share.go, network/client.go, network/message.go
This adds support for the innosilicon D9 on base firmware (`D9_20180602_094459.swu`), the hashchash supporting firmware is not supported because it does not confirm to the stratum spec.
=> multi: support innosilicon D9.

dividend/share_test.go, network/acceptedwork.go, network/job.go
This fixes a bug with `PruneAcceptedWork` and reverts deletion via cursors to deletion via buckets due to
inconsistent behaviour noticed with an identical test on dcrwallet. Deletion via buckets is the safest option since it's been tested in production.
=> multi: revert to deletion via buckets.

dividend/share.go, network/hub.go
This updates the pool diff helper to use 25 seconds as the max gen. time when calculating the appropriate
diffs for pool clients in solo pool mode where valid shares are a non-factor. The max gen. time was was kept under 30 seconds due to the likelihood of pool clients having timeouts of 30 seconds when there is no activity. This also updates the hashrates of the DR5 and D1.
=> multi: use higher share gen. time in solo pool mode.

dividend/share.go, miner/client.go, miner/cpuminer.go, network/hub.go, network/message.go
This refactors some helpers and the cpu miner. Share weights have been updated due to the updated hashrate of the DCR1. The getwork handler has been tweaked to try and fetch new work in 5 second intervals. Lastly the pool now tracks the mined blocks count.
=> multi: add mined blocks counter.

database/db.go, dividend/payment.go, dividend/payment_test.go, network/acceptedwork.go, network/endpoint.go, network/hub.go, pool.go
This tracks pool mode switches and backs up the db if necessary. Some refactoring has been done to
persist tracked values as they change instead of waiting till shutdown. Bugs related to persisting kvs
have also been resolved. New apis reporting the last work height and the last payment height have also been added.
=> multi: handle pool mode switches.

network/client.go, network/endpoint.go, network/hub.go
This enforces the max message size for a client's reader and reduces the ticker of the getwork handler to 1 second.
=> network: enforce max message size.

README.md, config.go, database/db.go, dividend/payment.go, dividend/payment_test.go, dividend/share.go, dividend/share_test.go, harness.sh, network/acceptedwork.go, network/hub.go, network/job.go, pool.go, util/conversion.go
This reworks the mined work tracking of the pool. Accepted work when confirmed as mined are marked as such. Processed shares are now pruned after generating payments from them.
An endpoint has been added to the api for database backups. The readme has been updated with the new endpoint as well.
=> multi: update mined work tracking.

cmd/miner/client.go, cmd/miner/cpuminer.go, cmd/miner/main.go, network/client.go, network/hub.go
This tracks the hashrate of pool clients and based on the intervals between their work submissions. This also fixes a bug with the cpu miner shutdown process where terminated goroutines were not signalling the waitgroup of being done.
The cpu miner connection handler is also less aggressive in reconnecting  to the pool when it drops, it now waits 5 seconds for every retry.
=> multi: implement realtime pool hash rate.

config.go
Include the param in the log message. Previously this was always
logging "nil".
=> fix error logging.

dividend/account.go, dividend/payment.go, dividend/payment_test.go, dividend/share_test.go, network/client.go, network/hub.go
This update account creation to use only the address to send mining rewards to for the
account.  This is more efficient compared to creating an account using the address and miner id.
This also betters hash rate formatting and fixes a bug with `FetchArchivedPaymentsForAccount`.
=> multi: better account creation.

network/acceptedwork.go, network/client.go, network/hub.go
This fixes the accepted work confirmation bug by fetching the parent accepted work of the connected
block instead of fetching the accepted work of the connected block first. This is being done because
it is possible for the accepted work of the connected block to be unavailable at the time its
corresponding block connected notification is received. It's also more efficient to directly fetch
the parent accepted work since that's ultimately the accepted work being confirmed.
Fixes #74.
=> network: fix accepted work confirmation.

dividend/payment.go, dividend/payment_test.go, gui/admin.go, gui/gui.go, gui/index.go, gui/templates/admin.html, gui/templates/index.html, network/acceptedwork.go, network/hub.go, pool.go
This fixes some issues with the gui which were introduced
in the previous commit. Also:
- Combine methods in hub.go so pool stats can be fetched in one call.
- Remove truncate param from method to fetch mined work
- Remove minNano param from method to fetch payments
- Reverse slices in index.go so payments and mined blocks
are displayed in reverse order. (This is temporary)
- index: show connected miners belonging to account
- move usage of util.HashString into the templates
- admin: show all connected miners
- Move AccountStats struct to gui package
- Add server side input validation to the Address form
- Combine functions FetchHash and FetchConnections so we only need to iterate
over connections once.
=> gui: show connected miners

network/client.go, network/endpoint.go, network/hub.go, network/message.go
This updates miner implementations to set the `extraNonce1` values for miners that do not fully comply to the stratum spec.
This also fixes client read/write related bugs as well as a connection counter decrement bug.
Fixes #81.
=> network: set extraNonce1 for non-complaint miners.

cmd/miner/config.go, cmd/miner/main.go, harness.sh
Running the test harness on a laptop is threatening to burn my house down. CPU mining on all cores by default is not ideal when working on a laptop.
This makes the max procs configurable.
=> miner: Make MaxProcs configurable

config.go, go.mod, gui/gui.go, pool.go
This adds support for letsencrypt issued certs intended for use in production. Additional config options have been added to allow specifying the domain the cert should be issued for.
=> multi: letsencrypt support.

cmd/miner/client.go, network/client.go, network/message.go
This fixes a bug where connected unauthorized and unsubscribed miners received work notifications as seen here:
```
❯ miner --configfile=client.conf --homedir=/home/dnldd/harness/c1
2019-06-11 17:58:37.546 [INF] MN: Version: 0.1.0+dev
2019-06-11 17:58:37.546 [INF] MN: Runtime: Go version go1.12.5
2019-06-11 17:58:37.546 [INF] MN: Home dir: /home/dnldd/harness/c1
2019-06-11 17:58:37.546 [INF] MN: Started miner.
2019-06-11 17:58:37.546 [TRC] MN: Miner generate blocks started.
2019-06-11 17:58:37.585 [TRC] MN: Started connection handler.
2019-06-11 17:58:37.585 [TRC] MN: Miner listener started.
2019-06-11 17:58:37.585 [TRC] MN: Miner hash rate monitor started.
2019-06-11 17:58:37.625 [TRC] MN: Message received is: (string) (len=413) …
```
=> multi: send work to only authorized and subscribed clients.

dividend/payment.go, gui/index.go, network/acceptedwork.go, network/client.go, network/hub.go
This asserts the generated account id exists before looking up work and payment data. Related error messages have been improved.
=> multi: assert account exists before work lookup.

config.go, gui/admin.go, gui/gui.go, gui/index.go, gui/public/images/charts.svg, gui/public/images/server.svg, gui/templates/header.html, gui/templates/index.html, pool.go, util/format.go
- Make pool designation configurable (as per the specification for VSP design)
- Show `PoolFee` and `Network` in Pool Information
Closes #93
=> Add PoolFee and Network to Pool Information

gui/index.go, gui/public/css/dcrpool.css, gui/templates/index.html, network/hub.go
- Add miner configuration info to the home page (Closes #86)
- Add links to the block explorer for payments (Closes #99)
- Fix an issue where GUI was completely broken in solo pool mode. It was hitting an error attempting to retrieve work quotas which were not available. This section of the front page is no longer drawn when the pool is in solo mode.
=> gui: display miner config info

cmd/miner/cpuminer.go, harness.sh
This updates the mining harness to only use testnet and simnet for testing, mainnet has been removed. A bug with the harness which prevented mining past stake validation height (SVH) was identified and fixed.
The harness provides scripts for mining and buying tickets, by default ticket purchases are done using the voting wallet's ticketbuyer.
This also stalls the miner after finding a block to prevent mining too quickly.
NB: To test, build the wallet on [dcrwallet PR #1484](https://github.com/decred/dcrwallet/pull/1484)
=> harness: mine past SVH.

cmd/miner/cpuminer.go, cmd/miner/main.go, config.go, dcrpool.go, pool/hub.go
This adds miner listening port configuration options to the pool. The old ports used are now the default
ports of the miners.
=> multi: miner port config.

pool/client.go, pool/message.go
This fixes an issue where the read goroutine of a client lingers due to the client sending invalid messages.
=> pool: fix client read goroutine termination.

README.md, config.go
This adds more detail on building, configuring and running dcrpool. `defaultRPCCertFilename` has also been removed.
=> multi: improve readme.

dcrpool.go, gui/gui.go, pool/hub.go
This removes context fields from structs with preference of passing them where needed, as should be for contexts. The expected hashrate for a cpu miner has been reduced further to make it easier to mine on cheap single core cloud servers.
=> multi: Pass contexts.

config.go, pool/chainstate.go, pool/endpoint.go, pool/endpoint_test.go, pool/hub.go, pool/hub_test.go, pool/payment.go, pool/payment_test.go, pool/paymentmgr.go, pool/pool_test.go
This fixes a channel sync issue with endpoint tests and adds `fetchPaymentsForAccount` for listing both pending and archived payments for an account.
=> multi: add fetchPaymentsForAccount.

cmd/miner/client.go, cmd/miner/config.go, config.go, pool/client.go, pool/endpoint.go, pool/hub.go
This resolves a case where a client stalling on current work doesn't receive timestamp-rolled work. Network difficulty log calculation errors and config related typos have been fixed as well.
=> multi: improve timestamp-rolled work.

cmd/miner/client.go, cmd/miner/cpuminer.go
This updates miner shutdown processes to avoid prematurely closing channels or blocking on a send or receive when shutting down, all processes fully terminate before the miner shuts down.
=> miner: fix miner shutdown panic.

pool/acceptedwork.go, pool/acceptedwork_test.go, pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/job.go, pool/job_test.go
This fixes a bug with the chainstate where disconnected mined blocks were deleted instead of being unconfirmed. Disconnected blocks are also used to unconfirm mined work if the mined work is the associated parent. Additional tests have been added accordingly.
=> pool: refactor & improve chainstate test coverage.

dcrpool.go
Using `mpLog` in the error handler for `loadConfig()` can cause a panic because this function is where the logger is initialised, and initialisation may not have occured yet.
```
error parsing config file: /home/jholdstock/harness/pool/pool.conf:15: unknown option: backup
Use dcrpool -h to show usage
2020-02-23 18:41:02.940 [ERR] MP: /home/jholdstock/harness/pool/pool.conf:15: unknown option: backup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa64506]
goroutine 1 [running]:
github.com/jrick/logrotate/rotator.(*Rotator).Write(0x0, 0xc0000ce200, 0x65, 0x78, 0x65, 0x0, 0x0)
/home/jholdstock/code/gopath/pkg/mod/github.com/jrick/logrotate@v1.0.0/rotator/rotator.go:133 +0x26 …
```
=> Prevent panic when logger is not initialised

dcrpool.go, go.mod, pool/hub.go, pool/paymentmgr_test.go
This refactors establishing node and wallet connections out of the hub which ultimately makes it easier to test. The hub's configuration struct has been updated to remove now unnecessary details.
=> multi: refactor connection creation out of hub.

dcrpool.go
This fixes a bug were the error from a `loadConfig` call was not getting outputted. dcrpool would exit without any errors as a result. Using `fmt` there instead of the logger because it's possible the logger is not initialized by `loadConfig` at the point where the error is generated.
=> fix loadConfig error output.

config.go, dcrpool.go, params.go
- Remove default dcrd user/pass and provide a descriptive error if they are not set.
- Remove default `WalletPass` and `PoolFeeAddr`. They were set to `""`, which is already the zero value for a string.
- Remove an errant `if` statement which was preventing the default config file from loading
- Ensure `PoolFee` is `>=0` and `<=1` in solo mode. **Question: Do we actually want to allow 0% or 100%?**
- Ensure `WalletPass` is provided when in solo mode.
- Ensure `PoolFeeAddrs` is provided when in solo mode, and also ensure it is properly split when multiple addresses are provided.
- If the pool cannot start, log error to stderr and finished with exit code 1.
- Automatically use the default main/test/sim network ports for dcrd/dcrwallet
=> Config improvements

dcrpool.go, gui/account.go, gui/admin.go, gui/assets/public/css/dcrpool.css, gui/assets/public/css/fonts.css, gui/assets/public/css/pagination.css, gui/assets/public/images/favicon/browserconfig.xml, gui/assets/public/images/favicon/manifest.json, gui/assets/public/js/carousel.js, gui/assets/public/js/modal.js, gui/assets/public/js/pagination.js, gui/assets/templates/account.html, gui/assets/templates/admin.html, gui/assets/templates/header.html, gui/assets/templates/index.html, gui/cache.go, gui/gui.go, gui/index.go, gui/middleware.go, gui/pagination.go, gui/websocket.go, pool/acceptedwork.go, pool/acceptedwork_test.go, pool/client.go, pool/client_test.go, pool/hub.go, pool/hub_test.go, pool/limiter.go, pool/limiter_test.go
As discussed on Matrix, bundling changes from #173 and #174 into a new PR with some additional changes.
This PR implements the new error modals as defined by @MariaPleshkova in https://xd.adobe.com/view/a814493c-193a-4dfc-5735-0e6d459a6924-de25/. These errors are displayed when an invalid URL is visited, for example `/account?address=NotARealAddress`. When you are searching for an account using the AJAX form, the errors should be displayed as before, this PR does not change those.
**Note:** This PR does not change the Javascript warning - that will need some extra thought because it cannot be implemented as a modal - drawing a modal depends on Javascript.
`Cache` has been introduced, which acts as a data buffer between hub and gui. Cache has setter functions which are used by the hub, and …
=> Introduce cache and more pagination.

cmd/miner/config.go, config.go, params.go, pool/message.go
- Use correct gRPC ports for dcrwallet.
- `cmd/miner` - log an error on invalid network selection
- Ensure difficulty is not zero - return 1 instead.
=> Use wallet gRPC

.github/workflows/go.yml, harness.sh
The number of mining clients created by the harness script can now be configured, up to a maximum of 20.
Also...
- Don't unnecessary new accounts on the mining wallet.
- Don't explicitly number tmux windows, this is not necessary.
=> harness: Configurable number of clients.

pool/hub.go, pool/hub_test.go
This checks the spendable amount available to the pool before making reward payouts. Previously
insufficient balance errors would be generated when publishing the transaction. This is more efficient/informative.
=> pool: check spendable balance before making reward payouts.

pool/client_test.go, pool/hub_test.go
This should resolve the intermittent failures of the previous last work time test by waiting for the work notification at client side before continuing with tests.
=> pool: update client last work time test.

gui/account.go, gui/cache.go, gui/index.go, gui/pagination.go
Homepage was showing some unconfirmed blocks due to the pagination endpoint not filtering correctly.
This PR has been updated to also include some improvements to the cache. The cache now performs all filtering and paging of data, rather than the calling code needing to do it. This is slightly more memory efficient, and also reduces duplication and simplifies calling code.
=> gui: Only display confirmed blocks on the homepage

README.md
harness needs dcrctl to work. Since dcrctl has it own repo now it needs to be installed separately from dcrd.
=> Add dcrctl install instructions for harness

harness.sh
The ":" while defining port made the profile service accessible on all interfaces. Now it only contains port number hence it defaults to localhost.
=> Fix harness to not expose profile

gui/account.go, gui/cache.go, gui/index.go, gui/pagination.go
There were a number of panics in pagination. 
1. If pagenumber or pagesize was 0 or negative.
```
https://localhost:8080/blocks?pageSize=-1&pageNumber=1
https://localhost:8080/blocks?pageSize=1&pageNumber=-1
```
2. If requested pagesize and pagenumber exceeded  work count. 
if count is 236 
then
```
https://localhost:8080/blocks?pageSize=1&pageNumber=237
https://localhost:8080/blocks?pageSize=2&pageNumber=119
etc
```
This PR fixes these issues.
=> Fix pagination panics

cmd/miner/client.go, cmd/miner/cpuminer.go, pool/message.go
This fixes a case where the read goroutine will hang when the miner is disconnected from the pool and a shutdown signal is received.
=> miner: fix miner shutdown on context signal.

gui/assets/public/css/dcrpool.css, gui/assets/templates/index.html, gui/assets/templates/pool-stats.html
Finishing touches to the GUI which completes the redesign.
Most significantly this removes hard-coded heights from the carousel so it is properly responsive to screen/window size. This also means we can update carousel content in future without having to readjust the hard-coded heights.
Closes #146
=> Complete GUI redesign

README.md, dcrpool.go, pool/acceptedwork.go, pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go
This uses tx confirmation notifications from the wallet to confirm the coinbases sourced by payments are spendable before attempting to spend them. The readme now  better explains why multiple pool fee address and multiple mining addresses are important to set in production.
Resolves #222 and #218.
=> multi: utilize tx confimation notifications.

pool/client_test.go, v1.1.0_release_notes.md
This extends read timeouts in client tests to prevent read timeouts on slow machines. This also fixes some formatting issues with the release notes.
=> multi: extend read timeouts in tests.

pool/client.go
This fixes a bug where the subscription state would be out of sync with the client because the response was getting sent before the state was updated.
=> pool: update client subscription state before responding.

gui/assets/templates/index.html
This removes the google hosted D9 firmware link in favour of the github hosted option.
Resolves #170.
=> gui: update Innosilicon D9 firmware link.

.github/workflows/go.yml, gui/assets/public/css/fonts.css
Discovered in decred/dcrdocs#1103, generic font-family names should not have quotes: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
Also taken the opportunity to update build deps.
=> Remove quotes from generic font-family names

go.mod, go.sum
This updates the rpcclient dependency to the latest due to a work notification reregistration bug fix.
=> go.mod: update rpcclient dependency.

gui/assets/templates/header.html
fonts.css should be loaded last to ensure dcr fonts take precedence over fonts in other css files
=> Load fonts.css last

.github/workflows/go.yml, README.md, harness.sh
- Add more detailed docs to the harness, remove details from project README
- Rename some vars in the harness to be more accurate:
- `NODES_ROOT` becomes `HARNESS_ROOT`
- `SESSION` becomes `TMUX_SESSION`
- tmux session is now `dcrpool-harness` rather than simply `harness`
- Create harness directory in `/tmp` rather than user home dir
- Create wallets with stdin rather than using tmux send-keys & sleep (decred/dcrwallet#1807)
Also including the update to go 1.15
=> Various harness updates

harness.sh
**Depends on #243**
This updates the harness to remove unneeded sleeps and utilize tmux's wait-for where applicable.
=> harness.sh: utilize tmux's wait-for.

gui/account.go, pool/acceptedwork.go, pool/acceptedwork_test.go, pool/account.go, pool/account_test.go, pool/chainstate_test.go, pool/client.go, pool/client_test.go, pool/db_test.go, pool/hub.go, pool/hub_test.go, pool/job.go, pool/job_test.go, pool/payment.go, pool/payment_test.go, pool/paymentmgr.go, pool/pool_test.go, pool/share.go, pool/share_test.go
There is currently an issue introduced by #245 where a disconnected miner is not able to reconnect because of an "account already exists" error:
```
2020-09-17 10:39:07.242 [DBG] POOL: Mining client connected. id=a42490b0/cpu, addr=127.0.0.1:36458
2020-09-17 10:39:07.263 [ERR] POOL: Account.Create: account 7f36b2c979067add6ce030176e0bdc75ac65798842f339aed8ad22d6cdda584c already exists
2020-09-17 10:39:07.283 [ERR] POOL: a42490b0/cpu: EOF
```
This PR fixes the issue by introducing and using a new func `CreateOrFetchAccount`. `CreateOrFetchAccount` will retrieve an account if one exists, or create one if not.
The check for address decoding is also moved into `CreateOrFetchAccount`. We only need to check for address validity once before inserting an account into the database, we don't need …
=> Use existing account if one exists

go.mod, go.sum, pool/chainstate.go, pool/chainstate_test.go, pool/paymentmgr.go
This updates picking the coinbase output from a tx base on the whether the treasury agenda is active or not.
Fixes #251.
=> multi: account for DCP0006 upgrade.

gui/account.go, gui/admin.go, gui/assets/public/css/dcrpool.css, gui/assets/public/js/admin-pagination.js, gui/assets/templates/account.html, gui/assets/templates/admin.html, gui/assets/templates/payments.html, gui/cache.go, gui/gui.go, gui/pagination.go, pool/db.go, pool/paymentmgr.go, pool/paymentmgr_test.go
Pending and archived payments to the pool are now displayed on the admin page.
First step towards #200
=> gui: Show pool payments.

gui/assets/public/js/admin-pagination.js, gui/assets/public/js/pagination.js, gui/assets/templates/payments.html, gui/cache.go
- List "Estimated Payment Height" for pending payments instead of CreatedOn.
- Display payment tables side-by-side on large screens. Maintain vertical stacking on smaller screens + mobile.
- Fix payment totals alignment issues
=> Remove CreatedOn timestamp from payments

config.go, dcrpool.go, pool/error.go, pool/error_test.go, pool/hub.go, pool/paymentmgr.go, pool/paymentmgr_test.go
This refactors the `payDividends` function into more targeted helper functions that are easier to test.
=> pool: refactor payDividends.

pool/acceptedwork.go, pool/account.go, pool/account_test.go, pool/chainstate_test.go, pool/client.go, pool/db.go, pool/db_test.go, pool/hub.go, pool/job.go, pool/job_test.go, pool/payment.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/share.go, pool/share_test.go, pool/upgrades.go, pool/upgrades_test.go
Regular conversion of database IDs between `string` and `[]byte` is necessary because bbolt expects all keys and values to be byte arrays. Because this is specific to bbolt and we want to generalise the code to work with other database implementations, the majority of our code should handle IDs as `string` and only convert to `[]byte` as close to the bbolt code as possible.
This has a nice side-effect of removing a large amount of inline type conversion.
Part of #257
=> Handle database IDs as strings where possible.

pool/acceptedwork.go, pool/acceptedwork_test.go, pool/account.go, pool/chainstate.go, pool/db.go, pool/db_test.go, pool/job.go, pool/payment.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/share.go
- Replace multiple duplicated funcs with a single generic func which takes bucket ID as an arg.
- Update tests to check for correct error type.
Part of #257
=> Remove duplicated fetchBucket funcs.

dcrpool.go, pool/acceptedwork.go, pool/acceptedwork_test.go, pool/account.go, pool/account_test.go, pool/boltdb.go, pool/chainstate.go, pool/chainstate_test.go, pool/client.go, pool/client_test.go, pool/database.go, pool/db_test.go, pool/endpoint.go, pool/hub.go, pool/hub_test.go, pool/job.go, pool/job_test.go, pool/payment.go, pool/payment_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/pool_test.go, pool/share.go, pool/share_test.go, pool/upgrades.go, pool/upgrades_test.go
All required database functionality is now defined in a new Database interface. Almost all of the production code has been updated to only handle this interface, rather than any concrete db implementations. This should enable the bbolt implementation to be switched out for a postgres implementation in future.
A big step for #257
=> Introduce Database interface.

pool/account.go, pool/account_test.go, pool/boltdb.go, pool/database.go, pool/job.go, pool/job_test.go, pool/payment_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/share.go, pool/share_test.go
- Move int64 <> byte conversion to boltdb.go because it is a generic bbolt helper used in multiple places.
- Various improvements to database accessor test coverage.  eg. checking errors more strictly, checking data fields are stored and retrieved correctly.
- Add fetchShare to Database interface. This is only used by test code, but its going to be needed for both BoltDB and PostgresDB, so it should be included in the interface.
- When inserting data, ensure database keys have not already been used. Return ErrValueFound if they have. Postgres will do this at the DB level, so enforcing the same checks in our BoltDB code helps to keep the interface and implementations consistent.
Improving the DB test coverage will help to ensure a Postgres DB implementation matches the Bolt DB …
=> Improve test coverage for DB accessors

pool/chainstate.go, pool/chainstate_test.go, pool/database.go, pool/payment.go, pool/payment_test.go, pool/upgrades.go
Following up from #276, a couple of additional changes.
- The first commit in this PR fixes a bug where archived payments were not having their UUID set correctly, the old value was being used. Using `NewPayment` to create the archive payment ensures all fields are set correctly, and also removes the need to call `time.Now` in the database code (duplicated in NewPayment).
- The second commit removes a lot of instances where we were recreating a payment ID with `paymentID()`, even though we already had it accessible in `payment.UUID`
=> Payment ID followup

dcrpool.go, pool/boltdb.go, pool/database.go, pool/db_test.go, pool/hub.go, pool/pool_test.go
This remove the behaviour which would automatically empty the database and create a new one when the pool mode was changed in config. The new behaviour is to log an error and prevent the pool from starting up.
The reason for this is the empty/backup behaviour does not map well onto other database implementations such as postgres, and after discussing with dnldd we agreed that its better for an admin to explicitly make the decision to backup and create a new DB, rather than the code doing it.
#257
=> Remove mode switching behaviour.

pool/hub_test.go, pool/paymentmgr_test.go, pool/pool_test.go, pool/share.go
First commit is fixing an existing bug in `paymentmgr_test.go`.
Second is breaking down the monolithic paymentmgr test in to smaller chunks. This enables more detail about test failures, and also removes database cleanup code from within the tests which will help with testing against different database implementations. (#257)
A third commit to only insert accounts into the test database when required. Previously 2 test accounts were inserted every time the test db was initialized, even though the accounts are only required for a small set of tests.
=> Remove database cleanup from payment manager tests.

pool/acceptedwork.go, pool/acceptedwork_test.go, pool/chainstate.go, pool/chainstate_test.go, pool/database.go, pool/payment.go, pool/payment_test.go, pool/paymentmgr_test.go
This PR contains multiple small improvements to testing code, most importantly improved test coverage for database code (supporting #257)
- Extra test coverage for DB code in `payments.go` and `acceptedwork.go`
- Properly check type of some errors in tests
- Remove helpers `persistPayment` and `persistAcceptedWork` which didnt really help much.
- Update Database interface so `deleteAcceptedWork` accepts an `id string` param, rather than an `AcceptedWork` struct.
=> Bundled test improvements

.github/workflows/go.yml, README.md, config.go, dcrpool.go, docs/postgres.md, go.mod, go.sum, gui/admin.go, gui/assets/templates/admin.html, harness.sh, pool/acceptedwork.go, pool/boltdb.go, pool/database.go, pool/db_test.go, pool/pool_test.go, pool/postgres.go, pool/share.go, pool/sql_queries.go
This commit adds a full postgres database implementation for dcrpool.
- New config items to enable postgres and set database connection details.
- Updated documentation to explain postgres usage.
- Database backup features are disabled when using postgres.
- All database tests are now run against both bolt and postgres database.
Closes #257
=> Postgres implementation.

pool/client.go
This fixes a bug where work submissions received in solo pool mining mode would be rejected even if the blockhash of the submission was less than the pool target for the mining client.
=> pool: fix solo pool rejected work submissions.

dcrpool.go, gui/cache.go, gui/gui.go, pool/account.go, pool/boltdb.go, pool/boltupgrades.go, pool/boltupgrades_test.go, pool/chainstate.go, pool/client.go, pool/database.go, pool/db_test.go, pool/endpoint.go, pool/hashdata.go, pool/hashdata_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr_test.go, pool/pool_test.go, pool/postgres.go, pool/sql_queries.go
This adds the hash data type which persisting client identification and hash rate information and integrates it into the gui cache. 
Resolves  #291
=> multi: integrate hash data type.

cmd/miner/client.go, harness.sh, pool/boltdb.go, pool/payment_test.go, pool/pool_test.go, pool/postgres.go
Previously these values were not being saved correctly because they were not being set when a new Payment was created in the DB code.
=> Set PaidOnHeight & TxID for archived payments.

gui/account.go, gui/admin.go, gui/assets/public/css/dcrpool.css, gui/assets/templates/header.html, gui/gui.go, gui/index.go
Disable account lookup form element and display a message to notify the feature is not available.
Closes #308
=> Disable account lookup on solo pools.

README.md, cmd/miner/config.go, config.go, harness.sh
This updates the `--homedir` flag to `--appdata` to be consistent with `dcrd` and `dcrwallet`. 
This is a breaking change. Normally deprecation would be preferred but since the upcoming release already has breaking changes 
and it'd not be great managing two homedir config vars with different values.
Resolves #307
=> multi: update a homedir config flag.

cmd/miner/client.go
This updates the miner to prune a request id once its associated response has been received. The miner now also only abandons a solve block process when it receives a clean job. Additional log outputs have been added to investigate an issue an regarding an unknown request response error.
=> miner: prune request ids.

pool/client.go
This fixes how client connections are terminated by the pool. Previously an empty message was being used to terminate the connection but this fails with i/o timeouts which would leave the connection in a false state of still being connected to the pool.
=> pool: fix client connection termination.

pool/client.go, pool/client_test.go
This removes an unnecessary work notification to clients that submit valid work submission. It's is unnecessary because additional work submissions can be found from the unexplored nonce space and if there is the need for updated work the timestamp rolled work process will provide that.
=> pool: superfluous work notif after submission.

cmd/miner/client.go, cmd/miner/cpuminer.go
This addresses some issues identified with the cpu miner in testing. Each issue has been addressed in a commit.
- miner: prioritize clean jobs:  
- This updates the miner to immediately begin solving new work if it is marked as a clean job.
- miner: avoid sending already known submissions:  
- This avoids sending already known submissions by comparing the previously sent submission nonce data to the newly solved nonce data and only proceeding if they do not match.
- miner: avoid submitting work when disconnected:  
- This updates the disconnection process to first update the solver and avoid work submissions.
- miner: fix possible read hang:  
- This fixes a case where process goroutine terminates on a context signal while the read process sends to its unbuffered read channel.
=> miner: avoid sending already known submissions. 

pool/client.go
This fixes a bug related to sending a set difficulty notification for an unsupported miner.
Work towards #316.
=> pool: fix set diff for unsupported miners.

errors/error.go, errors/error_test.go, pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/pool_test.go
This fixes chain notification messages being blocked by payment processing calls when tx confirmations are not accurately being reported.
The fix includes:
- ensuring a payment processing call concludes before starting another one via the processing flag.
- calling the payment process in a goroutine to avoid blocking the chain state process.
- keeping track of tx confirmation failures and starting a wallet rescan if the failures exceed threshold.
Associated tests have been updated.
=> multi: fix chain notif. blocking by pmt processor.

errors/error.go, errors/error_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go
This reworks coinbase confirmation function to uses the getTransaction grpc to fetch transaction details and confirm them. The rescan begin height is now a coinbase maturity length of blocks from the lowest reported block with a tx having inaccurate confirmation information. Tests have been updated.
=> multi: use getTransaction grpc for confirmCoinbases. 

.github/workflows/go.yml, pool/client_test.go, pool/message.go, pool/miner_id.go, run_tests.sh
Linter `golint` has been deprecated and replaced with `revive`.
=> Update to golangci-lint 1.40.1.

.github/workflows/go.yml, README.md, config.go, pool/boltupgrades_test.go, pool/db_test.go, pool/hub.go, run_tests.sh
Now that Go 1.16 is the minimum supported version, we can take advantage of new features introduced in 1.16.
- Use features from Go 1.16 tooling
- GO111MODULE environment variable now defaults to "on"
- "go build" and "go test" now exit with an error rather than silently modifying go.mod or go.sum files
- Update README.md
- Use latest linter
- Don't use deprecated ioutil package
=> Use go 1.16 features

errors/error.go, errors/error_test.go, go.mod, go.sum, pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/hub_test.go
This fixes a case where confirmations for a block having associated work cannot be found because it got reorged off the chain. The fix modifies the check to not error if the rpc error indicates the block cannot be found.
=> multi: fix pruning work for reorged blocks.

config.go, dcrpool.go, pool/boltupgrades_test.go, pool/client.go, pool/db_test.go, pool/hub.go
This updates all remaining cases of unwrapped errors in `fmt.Errorf` calls to wrap the underlying errors with the `%w` format verb to ensure they work nicely with `errors.Is` and `errors.As`.
=> multi: Wrap errors for better errors.Is/As support.

.golangci.yml, config.go, dcrpool.go, pool/boltupgrades_test.go, pool/client.go, pool/db_test.go, pool/hub.go
**This requires #345**.
This adds the `errorlint` linter to the list of linters.
=> build: Add errorlint linter.

pool/boltupgrades_test.go
It is not good practice to directly copy from a compressed archive to a file without chunking as it can lead to uncontrolled allocations should a file become corrupted.
=> pool: Do chunked decompress in pool tests.

config.go
**This is rebased on #349**.
This removes the unused error return from the `newConfigParser` function and updates the callers accordingly.
=> config: Remove unused err return on config parser.

config.go, dcrpool.go
**This is rebased on #350**.
This refactors the main code into a separate function that returns an error instead of invoking `os.Exit` directly to ensure that the defers that are setup prior to the exits are run as intended.
The `main` func will now exit with the non-zero error code when an error is returned from the refactored separate func.
=> main: Correct defer handling in main entrypoint.

dcrpool.go
**This requires #352**.
This defers the database close once opened to ensure it is always properly closed on all error paths.
=> main: Defer database close.

config.go, dcrpool.go, version.go, version_buildinfo.go, version_nobuildinfo.go
This reworks the way versions are handled internally to match other Decred projects such as dcrd and dcrwallet.  Namely, it reverse the semantics such that the individual semver components (major, minor, patch, prerelease, and buildmetadata) are parsed from a full string and exported at init time.
Also, since the version is now parsed and verified to be accurate, it updates the pre-release parsing to properly support dots as required by the spec.
Finally, starting with Go version 1.18, it adds the git commit hash to the version string as buildmetadata when no buildmetadata is otherwise specified.
This provides a few main benefits:
- Allows a single linker override to fully specify the version string instead of having separate ones that can only override the prerelease and build metadata …
=> version: Support single override and add git hash.

dcrpool.go, pool/hub.go
**This is rebased on #355**.
This moves the creation of the context into the main code path, splits the creation logic for the hub and gui into independent funcs, and arranges for the main code path to create those instances and run them.
Since the pool struct is no longer necessary, both it and the associated `newPool` func are removed.
This approach is preferred because it provides the main code path with full control over the lifecycle of the context instead of stuffing it into a separate struct which makes it much harder to reason about and has ultimately led to the use of the cancel func deep in the innards of the hub which should not have that level of control since it is not the coordinator and thus does not have enough details to know when it's actually safe or even should be …
=> main: Slightly rework main hub and gui lifecycle.

pool/chainstate.go, pool/chainstate_test.go, pool/endpoint.go, pool/endpoint_test.go, pool/hub.go, pool/paymentmgr.go, pool/paymentmgr_test.go
The waitgroup for the hub is currently being passed down into all various configuration structs for each of the goroutines it runs which requires a lot of plumbing and is quite error prone.
This addresses that by modifying the logic to keep the hub waitgroup local to the run method and removes the aforementioned unnecessary plumbing.
These changes have also exposed an issue with endpoint.run in that it never terminates, but this commit does not fix that issue.
=> pool: Keep hub waitgroup local.

config.go, pool/client.go
The chaincfg functions to get config params create a new instance on every invocation.  This avoids extra allocations by making use of the stored instances in the main package and storing the name of mainnet (which is the only use of it) in the pool module.
=> multi: Avoid extra chaincfg param instances.

pool/client.go, pool/hub.go
Check if the context is canceled before blindly sending to a channel which could be closed.
=> pool: Check ctx before sending to channel.

pool/endpoint.go, pool/endpoint_test.go
**This requires #358**.
This corrects the waitgroup logic in endpoint handling to ensure it properly terminates when the context is canceled.
It also enables the wait at the end of the endpoint test to help prove correctness.
=> pool: Correct endpoint waitgroup logic.

dcrpool.go, pool/client_test.go, pool/difficulty.go, pool/endpoint_test.go, pool/hub_test.go
This switches the calculation for the number of iterations to use the pow limit bit length as opposed to a less accurate round trip through a log2 float64 approximation.
=> pool: Use bitlen for calculating iterations.

pool/client.go, pool/client_test.go, pool/endpoint.go, pool/endpoint_test.go, pool/hub.go, pool/hub_test.go
This modifies the SubmitWork function to take the submission directly instead of a pointer to it.
Strings are already reference types, so there is no reason to take a pointer to a string unless the calee intended to change what the caller's string points at. Moreover, taking a pointer could also lead to unnecessary allocations.
=> multi: No string pointer on submit work.

pool/chainstate.go, pool/chainstate_test.go, pool/endpoint.go, pool/endpoint_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go
**This requires #359**.
Since the done channels are only used to signal completion by closing the channel, use a zero alloc `struct{}` for the type.
=> multi: Zero alloc for done chans.

harness.sh
Msys automatically transforms paths for executed commands, but it is unable to do that for paths in the config files.  This updates all of the paths in the config files to use relative paths instead so they work with the various processes.
It also use the posix compliant shebang for locating bash, adds a new variable to control whether or not the profiling ports are enabled, and disables postgres by default.
=> harness: Make the harness more Windows friendly.

dcrpool.go, internal/gui/gui.go
This updates the gui.Run method to block until the context is canceled as expected and then adds a waitgroup across both it and the hub to allow for clean shutdown of both subsystems prior to shutdown.
It also moves the initial connection and work acquisition prior to launching the subsystems to avoid launching them at all in the event of an error that would prevent the hub from initializing.
=> multi: Make GUI run blocking and wait for shutdown.

pool/client.go
The handler for subscribe requests seemed to have incomplete error handling for the case where FetchMinerDifficulty failed. No response was being returned to the caller.
This adds a generic Unknown error response so that the caller is not left hanging.
=> pool: Add missing response to subscribe handler.

internal/gui/cache.go, internal/gui/gui.go
**This requires #370**.
This consists of a series of commits that ultimately make the gui webserver respect the context and perform an orderly shutdown when it is canceled as well 
* First, it consolidates the logic that creates the GUI instance.
It's generally good practice to first create everything that can fail and then create the final instance at once with the results versus doing it piecemeal.
Piecemeal creation is typically more error prone and, while not a huge concern here, it also ends up needlessly creating objects that are just thrown away in the event of a later error.
* Second, it initializes the cache when GUI is created.
It accomplishes this by updating the init func to accept the config instead of individual components and moving the logic that acquires the details via …
=> gui: Rework create and run lifecycles.

pool/client.go, pool/endpoint.go, pool/hub.go, pool/hub_test.go
This switches client, hub, endpoint over to use the new pattern that consolidates the waitgroup logic in a single location.
This pattern is easier to reason about and less error prone since it's trivial to see at a glance that the calls to `Done` are happening as intended versus having to chase them down all over the code.
=> pool: Consolidate waitgroup logic.

pool/client.go
**This requires #373**.
This ensures the send to the read channel for a client respects the context since it could otherwise end up hanging forever when sending to the channel that no longer has a goroutine reading from it thereby leaking the goroutine.
It also includes the read goroutine in the overall waitgroup for the client to help ensure it shuts down as intended.
=> pool: Prevent potential read goroutine leak.

pool/client.go
**This is rebased on #375**.
This switches the code that examines read errors for timeout to use the proper interface from the net package that is designed for that purpose instead of digging into concrete types.
It also ensures clients that timeout without ever identifying themselves have their uniquely-assigned extra nonce used as the id instead so the log messages can be attributed to the ip of the offending clients.
Finally, it no longer logs an error when an `io.EOF` is encountered as that is an expected condition when the client disconnects and is not an actual error.
=> pool: Cleanup client read error logging.

dcrpool.go, internal/gui/gui.go
This creates the listener in the GUI constructor so any issues with listening will cause the entire pool to fail to start thereby allowing the admin to resolve any issues immediately.
=> gui: Create listener in GUI constructor.

pool/client.go, pool/endpoint.go
This removes the disconnect goroutine from the endpoint since it is not needed given each client is created with the context and shuts itself down when the context is canceled.
While here, this also updates each client to invoke their associated cancel function when shutting down to ensure it's always called as recommended.
=> pool: Remove unneeded client disconnect goroutine.

docs/postgres.md
This updates the postgres guide to include the latest versions of postgres which I've now tested and confirmed that they work as intended.
It also modifies the instructions to create a role with login and then create a database with that role as owner as opposed to creating a user that is then granted persmissions to the database.
This approach is generally preferred and all recent versions of postgres (versions >= 8.1) treat 'create user' as an alias for 'create role' with the login permission granted anyway.
As an aside, historically roles were allowed to own database objects while users were not, however, since users are actually just roles nowadays, there is no long a distinction.  However, it is still widely considered best practice to use 'create role' when the role will be the …
=> docs: Update postgres guide with tested new vers.

pool/endpoint_test.go
This modifies the endpoint tests to respect the context when sending to and receiving from the endpoint channels similar to what was recently done for the chainstate tests.
It also fixes a race in the test due to the add callback being invoked in the run goroutine.
=> pool: Make endpoint tests more robust and fix race.

.github/workflows/go.yml, docs/postgres.md
Update the build to use postgres 16.0 (following #384). I also bumped other build tools whilst in there.
Also added a quick one-liner to get postgres running in a Docker container for the database test suite.
=> Update build tools (postgres 16.0)

pool/boltupgrades.go, pool/hub_test.go, pool/paymentmgr_test.go, pool/pool_test.go, pool/share.go, pool/share_test.go
**This is rebased on #389**.
The postgres tests currently fail when running on fast systems due to the lack of a generating unique share IDs.
After digging into the failure a bit, the root cause is that the UUID used for the share id is not created with any randomness to it.
As the test failure demonstrates, it is generally not a good idea to rely solely on timestamps for generating supposedly unique values.  While it is fairly unlikely that two shares will come in at the same nanosecond in most cases, there are a variety of factors that can lead to such a situation.
So, this appends a random value to the share UUID in order to help ensure a unique overall value and updates the callers accordingly.  It also updates the database upgrade code to ensure the old share id format is used when …
=> pool: Improve share UUID with random value.

pool/paymentmgr.go
This ensures the goroutine in the payment manager that handles sending rescan responses respects the context so it does not potentially leak the goroutine if the context is canceled prior to receiving a response.
It also corrects the channel close logic by moving into the goroutine. As mentioned in previous commits, receivers should never close channels, only senders once they are sure there are no more goroutines that can write to the channel.
=> pool: Don't potentially leak paymgr goroutine.

config.go
The configs --minpayment and --maxtxfeereserve were deprecated in 1.1.0 and can be removed from the next release.
=> main: Remove deprecated configs.

pool/hub.go, pool/payment.go, pool/share.go
The UUID used for the payment ID was not created with any randomness to it, leading to occasional test failures due to duplicated values. Appending a random value to the UUID helps to ensure uniqueness.
The commit also updates the database upgrade code to ensure the old payment ID format is used when performing the old version upgrade.
=> pool: Improve payment UUID with random value.

pool/paymentmgr.go
This corrects the mutex logic in the payment manager that keeps track of whatever or not payments are already being processed.
In particular, the code that is being updated previously checked and set the processing flag under two separate locks of the mutex which could easily result in the first check returning false for two concurrent goroutines followed both both setting it to true and executing which would defeat the purpose of the check.
=> pool: Correct racy paymgr processing logic.

pool/acceptedwork_test.go, pool/chainstate_test.go, pool/client.go, pool/client_test.go
**This is rebased on #398**.
This modifies various pool tests to used mock client names instead of referencing specific models of ASICs which no longer exist.
=> pool: Use mock client names in tests.

internal/gui/assets/templates/index.html, pool/client.go, pool/client_test.go, pool/difficulty.go, pool/difficulty_test.go, pool/hashdata_test.go, pool/message.go, pool/miner_id.go, pool/share.go
**This requires #399**.
This removes all code related to ASICs that are no longer supported since they mine blake256 and the hash algorithm is now blake3.
The removals are done in separate commits to ease review.
In particular, support is removed for the following ASICs:
* Whatsminer D1
* Antminer DR5
* Antminer DR3
* Innosilicon D9
* Obelisk DCR1
=> pool: Remove code related to unsupported ASICs.

pool/share.go
This calculates the share weights in the global share weights map dynamically based on the entires in the map of the miner hash rates instead of hard-coding them to manually calculated values that can easily become outdated when the hash rates are updated.
=> pool: Calculate share weights dynamically.

pool/client.go
This renames the handler that sends work to a miner from `handleCPUWork` to `sendWorkDefault` and accepts the name of the miner as a parameter.
This is intended to help make it clear that it is sending the work and that it is the default format that all miners should ideally follow.
It also improves a couple of error messages while here.
=> pool: Rename cpu work handler to clarify default.

cmd/miner/client.go, pool/client.go, pool/client_test.go, pool/hub.go, pool/message.go
This modifies the pool to report the entire partial header via the first generation tx field as intended and no longer populates the second generation tx field since it does not apply to Decred.
Some of the old ASICs hacked the stake version in there, but that is really not something that should have ever been done because the stratum "protocol" (which is not actually very well defined) already does not individually provide all of the information the Decred header needs nor does it provide an official way to extend it.
Further, the Decred header explicitly provides additional space which removes the need to create a new coinbase and update the merkle root.
So, in order to address these things, the field that was intended to serve for the coinbase (generate transaction) was repurposed to …
=> pool: Do not populate/use gentx2.

pool/chainstate_test.go, pool/client.go
There is no reason to explicitly call .String in format statements since they automatically invoke it because it implements fmt.Stringer.
=> pool: Use fmt.Stringer.

pool/hub.go
This clamps the max generation time threshold to the target block time for the active network since it doesn't make any sense for it to be longer.  It is also needed for proper simnet support since the defaults are longer than the target block time there.
=> hub: Clamp max gen time to target block time.

pool/client.go, pool/client_test.go, pool/hub.go
This modifies the pool to work with BLAKE3 as now required by the Decred network.
In particular:
- All submissions are now checked against BLAKE3
- The padding semantics for the underlying `getwork` communications now match the padding of BLAKE3 as required
- The work submissions in the tests are now updated for BLAKE3 padding semantics, solved using BLAKE3, and updated with the solutions accordingly
=> pool: Update for BLAKE3.

internal/gui/assets/templates/index.html, pool/client.go, pool/difficulty.go, pool/message.go, pool/minerid.go
**This requires #406**.
This adds gominer version 2.0.x as a supported mining client.
=> pool: Add gominer 2.0.x support.

cmd/miner/cpuminer.go, pool/client.go
blockHash is used to construct the AcceptedWorkID when retrieving AcceptedWork from the database, not the powHash.
Because of this bug, dcrpool was failing to register when a block mined by the pool had been confirmed, thus it was never sending the coinbase from that block to the mining participants.
=> Use blockHash for AcceptedWorkID, not powHash.

internal/semver/semver.go, internal/semver/semver_test.go, pool/minerid.go, pool/minerid_test.go, version.go
This reworks the client user agent identification logic to improve its efficiency and flexibility as well as to easily support old minor versions.
It does this by changing the matching logic to first parse the user agent into its individual components and then attempting to match against that parsed information using matching functions as opposed to encoding the more specific matching logic directly into a regular expression.
The user agent parsing first attempts to split it into a client name and version part and when that is successful further attempts to parse the version part into the individual semantic version components using a regular expression with capture groups.
The matching functions are closures that accept the parsed user agent details and may impose arbitrary criteria.
For …
=> multi: Rework client user agent id logic.

harness.sh
Local clients running on simnet are known and trusted, so there is no need for the banning feature of dcrd to be enabled.
=> harness: Disable dcrd banning.

pool/hub.go, pool/paymentmgr.go, pool/paymentmgr_test.go
- Wrapping the TxCreator and TxBroadcaster in Fetch funcs adds lots of boilerplate code but offers no tangible benefit in return.
- The txCreator and txBroadcaster interfaces are not used anywhere other than the pool package so they don't need to be exported.
=> Remove unnecessary Fetch funcs for txBroadcaster and txCreator

pool/chainstate.go, pool/paymentmgr.go, pool/paymentmgr_test.go
The only reason dcrpool needs to be aware of DCP-0006 activation is to determine the index of the coinbase output, so rather than passing around a treasuryActive bool, the index itself can be passed around.
=> pool: Remove treasuryActive bool from func sigs.

pool/hub.go, pool/paymentmgr.go, pool/paymentmgr_test.go
Reverts part of #418 
These funcs were mistakenly removed because they seemed to be unnecessary, but actually they are required due to the extremely tight coupling between PaymentManager and Hub. Removing them is possible, but requires more involved work to untangle the construction of the two components.
=> pool: Reinstate Fetch txBroadcaster/txCreator.

pool/paymentmgr.go, pool/paymentmgr_test.go
Minor improvements made whilst investigating #425.
Note that this includes changing an assertion in the test `testPaymentMgrDust`
=> Miscellaneous payment manager refactoring.

internal/gui/assets/templates/account.html
The miner ip:port are already present in the connected client info so they can be displayed on the account page with only a minor change.
Previously only the name of the miner software and the hashrate were displayed which made it impossible to distinguish which client was which. Having the ip:port of the client isn't much better, but it's definitely better than nothing.
=> gui: Display miner ip:port on account page.

go.mod
Only Go 1.21 is actually required.  The addition of the toolchain line makes it require Go 1.22.3 which is not at all necessary and 
should not be there.
=> build: Remove unnecessary toolchain from go.mod.
