config.go, go.mod, harness.sh, miningpool.go, routes.go, sampleconfig.go
This adds the active network to the config and asserts all addresses provided are for the
active network.
=> main: set the active network.

database/db.go, dcrpclient/cpuminer.go, worker/share.go, ws/client.go, ws/work.go
This persists accepted work submitted by the pool.
=> multi: persist accepted work.

config.go, dividend/payment.go, network/hub.go, pool.go
This implements the PPLNS payment scheme and adds a last n period parameter to the configuration.
=> multi: implement pay per last n shares.

config.go, go.mod, network/hub.go, pool.go, sampleconfig.go
This implements PayoutDividends which creates, signs and publishes a transaction.
=> multi: add PayoutDividends.

dividend/payment.go, dividend/payment_test.go, dividend/share.go, dividend/share_test.go, poolclient/config.go
This adds tests for the db time range scan, PPS and PPLNS payment schemes.
=> multi: add payment scheme tests.

config.go
This removes the mining address config option because the pool does not need to track mining
addresses used. This will be handled by the mining node.
=> main: remove mining address config option.

run_tests.sh
This adds a simple script to run all tests in the project.
=> main: add run_tests.sh

dividend/payment_test.go
This adds payment amount summation tests to PPS and PPLNS tests.
=> dividend: add summation tests.

dividend/payment.go, dividend/payment_test.go, dividend/share.go, network/hub.go
This updates the payment struct to track the height at which the payment was generated at. A payment bundle struct has been added to group payments to accounts. All payment schemes have been updated as well as corresponding tests.
=> multi: update payment struct.

dividend/account.go, dividend/payment.go, dividend/payment_test.go, dividend/share_test.go, network/hub.go
This refactors payment related helpers as well as test related helpers and adds payment detail tests.
=> multi: add payment detail tests.

network/hub.go
This removes `GeneratePaymentDetails` hub method in favour of the `GeneratePaymentDetails` function and updates call sites accordingly.
=> network: remove GeneratePaymentDetails hub method.

entity.go, network/hub.go, poolclient/main.go
This updates notification parsing and temporarily disables block processing for connected and disconnected blocks.
=> multi: update chain notifications processing.

network/client.go, poolclient/client.go
This is a first of multiple improvements to the pool's  processing of work submissions. Work submissions are asserted to be below the network target difficulty before being relayed.
=> multi: assert work submissions.

poolclient/cpuminer.go
This is a first of multiple improvements to the pool's  processing of work submissions. Work submissions are asserted to be below the network target difficulty before being relayed.
=> poolclient: update cpu mining.

harness.sh
This updates the mining harness to incorporate a wallet.
=> harness: update mining harness.

config.go, dividend/account.go, dividend/payment.go, dividend/share.go, entity.go, harness.sh, network/acceptedwork.go, network/client.go, network/hub.go, pool.go, poolclient/client.go, routes.go
This refactors helper functions related to the payment schemes, the entity interface has been updated to remove the status field on the delete function. Specialized eligible shares  functions have also been provided for each payment scheme.
The payment bundle, tx creation, funding and publishing have been reworked and tested. Lastly the
harness has been updated to incorporate PPLNS testing configuration.
=> multi: refactor payment scheme pipelines. 

dividend/payment.go, network/hub.go
This adds helpers to prune payments processed approximately 30 days ago. Matured payments are now processed with every connecting block.
=> multi: prune old payments.

database/db.go, dividend/account.go, dividend/payment.go, harness.sh, network/acceptedwork.go, network/hub.go, pool.go
This upgrades the test harness by separating the ticket buying wallet and the pool wallet, the pool node is also separated from the network master node. A payment archive bucket has also been added to store processed payments for auditing purposes. This also includes additional bug fixes related to fetching  entities from the db and dcrpool shutdown.
=> multi: upgrade test harness.

dividend/payment.go, dividend/payment_test.go
This adds a helper for fetching archived payments using the filtering parameters provided. A corresponding test for the helper has been added.
=> dividend: fetch archived payments for account.

README.md, harness.sh, network/hub.go
This adds a readme to the project and improves the start time of the harness.
=> multi: add README.

README.md
This adds the travis build status and tweaks the readme structure.
=> readme: update README.

harness.sh, miner/client.go, miner/cpuminer.go, network/client.go, network/limiter.go, network/message.go
This updates the test harness expecially the dcrd config. It also fixes a some bugs with the cpu miner and the requests rate limiter.
=> multi: update harness.

README.md, dividend/share.go, network/client.go, network/message.go
This adds support for the whatsminer D1 and updates the readme accordingly.
=> multi: support whatsminer D1.

cmd/miner/client.go, cmd/miner/cpuminer.go, dividend/payment.go, harness.sh, network/client.go, network/hub.go, network/message.go
This updates the work notification pipeline due to a bug that was leaving connected miners on
stale work each update cycle. This also improves log messages outputted and reverts an update
that broke json-rpc compatibility for notifications. This also removes the username requirement in
order to be authorized by a pool when solo pool mode.
=> multi: update work notification pipeline.

.gitignore, cmd/miner/cpuminer.go, config.go, dividend/share.go, harness.sh, network/acceptedwork.go, network/client.go, network/endpoint.go, network/hub.go
This updates the harness for PPS and PPLNS tests on simnet as well as fixing a bug related to
disconnected pool clients still being referenced by their endpoints. A bug which prematurely deleted mined work found by multiple pool clients has also been fixed.
=> multi: payment scheme tests.

database/db.go, dividend/share.go, harness.sh, network/acceptedwork.go, network/hub.go, pool.go
This adjusts the max generation time in solo pool mode for a higher difficulty for all miners. A bug
related to persisting the mined blocks count has been fixed as well.
=> multi: tune mining difficulty.

README.md, config.go, harness.sh, pool.go
This documents the pool api and acknowledges the people who have contributed to dcrpool so far.
This also makes the api port configurable.
=> multi: document pool api.

README.md, harness.sh, network/hub.go, pool.go
This removes some local defaults  from the harness for better compatibility, a harmful simnet nuking snippet was also removed.
=> multi: harness fixes.

cmd/miner/client.go, cmd/miner/cpuminer.go, cmd/miner/main.go
This implements miner reconnections for the cpu miner and also restructures how miner process lifecyles are handled.
=> miner: implement miner reconnections.

config.go
This updates config file generation to use lowercase names and also persist all options with their
descriptions.
=> config: fix config generation.

harness.sh
- harness: add logging
- harness: run dcrpool in repo root
- this ensures that dcrpool is able to access local assets (eg. html templates)
=> harness: add logs 

.gitignore, config.go, dividend/payment.go, gui/admin.go, gui/gui.go, gui/index.go, gui/public/css/dcrpool.css, gui/public/images/blockHeight.svg, gui/public/images/blockrewardOpen.svg, gui/public/images/cryptocurrency.svg, gui/public/images/miningPow.svg, gui/templates/admin.html, gui/templates/footer.html, gui/templates/header.html, gui/templates/index.html, gui/templates/login.html, network/hub.go, pool.go, util/format.go
- validate payment scheme has been set correctly in config
- display the quota as a percentage rather than rational (ie. `20%` instead of `1/5`)
- if no payment quotas are found, return an empty map rather than an error
- do not return payment method whilst fetching work quotas. Take the payment scheme from config instead.
=> gui: move work quotas from admin page to homepage

gui/public/css/dcrpool.css, gui/public/images/search.svg, gui/templates/header.html, gui/templates/index.html
=> gui: Move search bar into page header

gui/gui.go, gui/index.go, gui/public/css/dcrpool.css, gui/templates/footer.html, gui/templates/index.html, util/format.go
- Format unix time properly
- Include account ID when showing address details
- Link to admin page in footer
- Add spaces to table headers
- Links to dcrdata.
- Re-org columns of payments table.
=> gui: Fix minor issues.

dividend/payment.go, dividend/payment_test.go, network/hub.go
**DO NOT MERGE**
This will be updated after a refactoring pr in the works is merged.
=> multi: track transaction ids for confirmed payments.

intro.md
This add dcrpool's introductory post to the repo for edits and feedback.
=> intro: add introductory post.

dcrpool.go, gui/admin.go, pool/client.go, pool/error.go, pool/hub.go
=> muti: fix client hash rate calculation.

dcrpool.go, gui/admin.go, gui/gui.go, gui/websocket.go, pool/hub.go
=> multi: fix nil ref bugs.

gui/assets/public/css/dcrpool.css, gui/assets/public/js/socket.js, gui/assets/public/js/tablesort.number.min.js, gui/assets/templates/header.html, gui/assets/templates/index.html, gui/formatting.go, gui/gui.go, gui/websocket.go
=>  gui: Automatically update blocks mined by pool

gui/gui.go
#114 was raised in error, the code is functioning correctly. I am adding my debug logging in this PR anyway, its kinda useful to have
=> gui: Log listening ports

gui/websocket.go
```
==================
WARNING: DATA RACE
Read at 0x00c000191590 by goroutine 31:
runtime.mapiterinit()
/usr/lib/go-1.12/src/runtime/map.go:804 +0x0
github.com/decred/dcrpool/gui.(*GUI).SendUpdatedValues()
/code/jholdstock/dcrpool/gui/websocket.go:61 +0x371
github.com/decred/dcrpool/gui.(*GUI).Run.func2()
/code/jholdstock/dcrpool/gui/gui.go:283 +0xad
Previous write at 0x00c000191590 by goroutine 101:
runtime.mapassign_fast64()
/usr/lib/go-1.12/src/runtime/map_fast64.go:92 +0x0
github.com/decred/dcrpool/gui.(*GUI).RegisterWebSocket()
/code/jholdstock/dcrpool/gui/websocket.go:43 +0x170
github.com/decred/dcrpool/gui.(*GUI).RegisterWebSocket-fm()
/code/jholdstock/dcrpool/gui/websocket.go:35 +0x5f
net/http.HandlerFunc.ServeHTTP()
/usr/lib/go-1.12/src/net/http/server.go:1995 +0x51 …
```
=> gui: fix race on websocket client list

cmd/miner/config.go, cmd/miner/main.go, config.go, dcrpool.go, harness.sh
This adds profiling config options to the mining pool and the cpu miner and removes a dependency on existing dcrd config and rpc cert in setting up dcrpool. This allows further simplification of the harness.
The harness is also now configured for simnet only.
=> multi: remove dcrd config dependency.

cmd/miner/client.go, cmd/miner/cpuminer.go, config.go, pool/acceptedwork.go, pool/account.go, pool/client.go, pool/hub.go, pool/limiter.go, pool/message.go, pool/share.go, pool/share_test.go
This mainly updates diff and target calc. by using a higher precision type. Some refactoring and documentation updates have also been done.
=> multi: use higher precision type for target & diff.

pool/acceptedwork.go, pool/acceptedwork_test.go, pool/account_test.go, pool/db.go, pool/db_test.go, pool/hub.go, pool/job.go, pool/job_test.go, pool/limiter_test.go, pool/payment.go, pool/payment_test.go, pool/pool_test.go, pool/share_test.go
This adds extensive tests for most pool components. Additional work will have to be done to decouple other pool components and write tests for them as well.
=> pool: improve test coverage.

gui/admin.go, gui/gui.go, gui/index.go, gui/websocket.go
Bundled into a single PR for convenience. See individual commits for further information.
=> Miscellaneous minor improvements for GUI

pool/acceptedwork.go, pool/acceptedwork_test.go
This adds an additional check to listing functions  for accepted work and updates tests accordingly.
=> pool: improve test coverage for accepted work.

README.md, config.go, dcrpool.go, pool/client.go, pool/difficulty.go, pool/message.go, pool/share.go
=> multi: add obelisk DCR1 support.

pool/client.go, pool/client_test.go, pool/endpoint.go, pool/message.go
This updates stratum errors to provide more detail to clients and adds more tests covering negative paths.
=> pool: improve test coverage for pool client.

gui/assets/public/css/dcrpool.css, gui/assets/templates/account.html, gui/assets/templates/admin.html, gui/assets/templates/index.html, gui/assets/templates/pool-stats.html, gui/formatting.go
This can be merged before #158 without causing any errors, but if it is, the DCR1 port will not be displayed in the GUI until 158 goes in.
It's unfortunate that the carousel height needs to be manually incremented when a the text inside it changes. Its a limitation inherited from the carousel code taken out of the VSP site. I will see if we can improve that.
(Part of #110)
=> Add Obelisk DCR1 to gui.

pool/client_test.go
This adds  tests for  the Obelisk DCR1 to ensure it can subscribe for work and receive notifications,
claim shares and submit work.
=> pool: add DCR1 client tests.

pool/difficulty.go, pool/endpoint_test.go, pool/limiter.go, pool/limiter_test.go, pool/payment_test.go, pool/share_test.go
This adds additional tests to payments and endpoints, and fixes a bug with the rate limiter where an unknown client type is passed to `withinLimit`.
=> pool: improve test coverage for payments.

README.md, pool/db.go, pool/db_test.go, pool/hub.go, pool/hub_test.go, pool/pool_test.go
This adds tests for all bolt db bucket helpers as well as coverage for negative db initialization paths.
The pool database is now backed up before shutdown.
=> pool: improve test coverage for bolt db.

cmd/miner/client.go, cmd/miner/config.go, config.go, pool/acceptedwork.go, pool/acceptedwork_test.go
Tidying up a few unrelated things I noticed whilst implementing #163
=> Miscellaneous tidying

pool/hub_test.go
This adds more tests covering hub additional functionality.
=> pool: improve test coverage for pool hub.

dcrpool.go, gui/gui.go, pool/chainstate.go, pool/client.go, pool/endpoint.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go
This sets up cache refresh signals from the pool to the gui.
=> multi: add cache refresh signalling.

gui/assets/public/js/socket.js, gui/gui.go, gui/websocket.go, pool/hub.go
Websocket server is now decoupled from the gui, and it is possible to send individual values through the sockets.
=> gui: Send individual values through websocket

pool/hub.go
=> pool: log outgoing payments.

dcrpool.go, gui/account.go, gui/assets/public/css/dcrpool.css, gui/assets/public/images/indicator-failed.svg, gui/assets/public/images/indicator-finished.svg, gui/assets/public/images/indicator-in-progress.svg, gui/assets/public/images/indicator-upcoming.svg, gui/assets/templates/account.html, gui/assets/templates/admin.html, gui/gui.go, pool/hub.go
Closes #138 
A button is added to the pending payments table which allows requesting payment. Confirmation is displayed in a modal, and then the button is hidden. The button is only displayed if Javascript is enabled.
Also, the whole pending payments section is now hidden if an account has no pending payments due.
=> gui: Allow users to request payment

config.go
=> config: Only allow pool fee between 0.2% and 5%

gui/account.go, gui/assets/templates/account.html, gui/gui.go
Payments are now paid as soon as possible, when the coinbase matures. This makes the "Request Payment" feature redundant.
=> gui: Remove payment requests

gui/cache.go, gui/pagination.go
=> Pagination fixes

gui/account.go, gui/admin.go, gui/cache.go, gui/index.go
This updates the gui cache to use pointer slices avoiding extra allocations in fetch calls.
=> gui: utilize pointer slices for cache.

README.md, gui/index.go, gui/middleware.go, pool/message.go, pool/paymentmgr.go, v1.1.0_release_notes.md
This updates the readme with detailed info on what pool fee constitutes as well as the source of tx fees for payout transactions. This also does some clean up.
This also adds the v1.1.0 release note to the repo for collaborative editing purposes, will be removed once its finalized.
=> multi: update readme with tx & pool fee details.

pool/client.go, pool/client_test.go, pool/endpoint.go
remove context from client.run.
=> pool: add context to NewClient.

gui/admin.go
=> Don't write http body on db write error

harness.sh
One instance of renaming missed in #243
=> harness: Fix TMUX_SESSION var name

pool/db.go, pool/hub.go
=> Extract db code from hub.go

pool/acceptedwork.go, pool/chainstate.go, pool/chainstate_test.go, pool/job.go, pool/payment.go
=> Extract db code from chainstate.go

pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/payment.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/share.go
=> Extract db code from paymentmgr.go

pool/db.go, pool/db_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/share.go
=> Extract more db code from paymentmgr.go

config.go, dcrpool.go
This updates the wallet gprc credentials setup to incoming v1.6.0 requirements.
S/O to @jrick  for the heads up.
=> update wallet grpc credentials setup.

dcrpool.go, gui/admin.go, gui/gui.go, pool/acceptedwork_test.go, pool/account_test.go, pool/chainstate.go, pool/chainstate_test.go, pool/client.go, pool/client_test.go, pool/db.go, pool/db_test.go, pool/endpoint.go, pool/endpoint_test.go, pool/hub.go, pool/hub_test.go, pool/paymentmgr.go, pool/paymentmgr_test.go, pool/pool_test.go
As agreed with @dnldd, this PR will contain all of the additional work required before introducing a database interface. I will mark this as a draft and only approve it once all of the necessary changes are included. Each commit will be a standalone change with a proper description, so they can be reviewed individually. The next PR following this one will be the interface.
Part of #257
=> Final changes before introducing database interface

run_tests.sh
Also add some code to `run_tests.sh` so we can avoid this issue happening in future.
=> ci: Fail build if go.{mod,sum} change.

pool/db_test.go, pool/pool_test.go
More test coverage to support #257
=> Add tests for CSRF secret.

pool/client_test.go, pool/difficulty_test.go
Check some error types properly, rather than just checking `!= nil`
=> Check error types in tests.

config.go, dcrpool.go, harness.sh, pool/boltdb.go, pool/database.go, pool/pool_test.go, pool/postgres.go, pool/sql_queries.go
This updates the pool startup process to purge an existing postgres db on startup for simnet testing purposes.
=> multi: update harness db startup.

pool/client.go, pool/difficulty.go, pool/miner_id.go
This adds a nicehash pool verificator client entry to supported mining clients.
=> pool: add nicehash pool verificator support.

pool/db_test.go
Implemented for vspd, so figured we might as well take it in dcrpool too.
=> Add extra assertions for database HTTP backup test

config.go
Add a version config item which will cause the application to print version information and then exit.
=> Add version command.

gui/assets/templates/index.html, gui/cache.go, gui/index.go
This fixes pagination related errors when the data source returns nil. The supported miner list has also been updated.
Closes #292
=> gui: fix pagination errors.

pool/boltdb.go, pool/chainstate.go, pool/client.go, pool/database.go, pool/endpoint.go, pool/hashdata_test.go, pool/hub.go, pool/postgres.go
This fixes a bug related to hash calculations spanning multiple cycles.
=> pool: fix hash calc spanning multiple cycles.

pool/boltupgrades.go
Don't run with database versions which are newer than dcrpool currently understands.
=> Don't try and run with upgraded databases.

cmd/miner/main.go, cmd/miner/signal_unix.go, dcrpool.go, signal_unix.go
=> Add SIGTERM and SIGHUP to shutdown signals.

.golangci.yml, cmd/miner/cpuminer.go, gui/gui.go, pool/chainstate.go, pool/hub.go, pool/message.go
**This requires #343**.
This adds the dupword linter to the list of linters.
=> build: Add dupword linter.

config.go, dcrpool.go
**This requires #351**.
This modifies the initial configuration error handling logic to match dcrd.  In particular, the logic is modified to avoid a bunch of duplicate code and fix some cases that were not logging the errors as expected.
It accomplishes this by consolidating the error reporting in a single place in the caller and introducing a custom error type which signals that the usage message should be suppressed in order to retain the primary behavior the originally was the reason for the prints being in the config function to begin with.
Also, the application name is passed into the function now since it is needed in both places.
=> config: Consolidate error reporting.

pool/client.go
This modifies the new client logic to create the extra nonce before to creating the client and using it during initialization.  Constructors should generally handle everything that can error prior to creating the object since it is wasteful to create an object only to immediately throw it away when there is an error.
=> pool: Gen extra nonce before initialize.

dcrpool.go, pool/chainstate.go, pool/chainstate_test.go, pool/hub.go, pool/hub_test.go
The pool is currently designed to shutdown the entire process deep down in the chainstate when some errors it deems to be fatal occur.  It accomplishes this by passed the cancel func for the entire process all the way down to the chainstate.  Unfortunately, this is not a good design because goroutines deep in the guts of subsystems should not have the ability to directly pull the rug out from under the under process without the upper layers having a chance to do anything about it.
Moreover, some of those errors could actually be temporary errors such as temporary loss of connection to the database or dcrd which then result in the entire process shutting down.
This is a first pass at improving the situation slightly by no longer passing the entire process's cancel func down the chainstate …
=> pool: Don't give chainstate entire process cancel.

dcrpool.go
The profiling server typically shouldn't be exposed to the public, so this doesn't make a huge difference, but it's still good practice for HTTP servers to have read timeouts.
=> main: Add read header timeout to profile server.

README.md
This consists of a series of commits that update the main `README.md` to match the current status and reality as well as address a few other things.
=> docs: Update README to match current status.

pool/pool_test.go
This modifies the pool tests to avoid cleaning up the postgres data when there is a test failure and the `-failfast` test flag is set so the contents of the database can be examined.
Since a failed run with `-failfast` will no longer purge the data, it also adds logic to purge the data prior to running the tests to ensure any previous failed runs are cleaned up on subsequent runs.
=> pool: Leave failed postgres db state in pool tests.

README.md
=> docs: Update README for BLAKE3/DCP0011 support.

pool/chainstate.go
Wrapping the notification handlers into functions means that the msg.Done channel only needs to be closed in a single place, rather than having it closed before every continue/return (which is annoying and very error prone).
Looks like a huge diff but its mostly indentation.
=> pool: Wrap ChainState notifications handlers.

pool/paymentmgr.go
The code to calculate payment amounts was overly complicated and duplicated 4 times. This change simplifies it and adds some comments.
=> pool: Simplify code calculating rewards payments.
